nelmio_api_doc:
    use_validation_groups: true
    documentation:
        info:
            title: Snorri
            description: Réseau social RI7
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc(?:\.json)?$)
